version: "3.11"

services:
  app:
    build:
      context: .
    ports:
      - '8003:8003'
    volumes:
      - ./app:/app
    command: >
      sh -c "python migrate &&
             python runserver 0.0.0.0:8003"
